### ISSUE TITLE
better readme/install instrucitons?

### ISSUE THREAD

**Issue by Nsomnia** [Sidmaz666/qtile-rofi-keybindings#1]
Was looking for something like this ever since starting qtile over xmonad since I mlove awesomewm's hotkey popup key bindings cheatsheet. 

Tried twice on 2 systems and doesnt seem to work, tried running the installer and then the normal command as well as the python script with and without su priv but just pops up the cheathseet with 1 blank entry.

Amy tips?

**Comment by Sidmaz666** [comment]
@Nsomnia make sure you run the install.sh script with sudo command, if your qtile config file located somewhere else beside the default path $HOME/.config/qtile/config.py then use the --custom or -c flag and enter the exact path of the qtile config file. it is also important that your qtile config file is well formatted. checkout my [qtile config](https://github.com/Sidmaz666/dotfiles/blob/main/.config/qtile/config.py) file if that helps. It's hard to pinpoint what sort of issue you are facing can you please provide more details such as what does your terminal shows or something like that
